
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
camera: !include cameras.yaml
discovery:
  ignore:
    - yeelight

frontend:
  themes:
    happy:
      primary-color: pink
    sad:
      primary-color: blue



#################################################################
## Logging
#################################################################
logger:
  default: critical
  logs:
    # log level for HA core
    default: info
    homeassistant.components.mqtt: warning
    homeassistant.components.apcupsd: debug
    homeassistant.components.lifx: warning
#################################################################
## Components
#################################################################


utility_meter:
    daily_energy:
      source: sensor.combined_energy_total
      cycle: daily

    monthly_energy:
      source: sensor.combined_energy_total
      cycle: monthly
      offset:
        days: 20

yeelight:
  devices:
    192.168.5.23:
      name: porch_bulb

wemo:
  discovery: false
  static:
    - 192.168.5.50

apcupsd:
    host: 192.168.5.12
    port: 3551

weather:
  - platform: openweathermap
    api_key: c488bcccdef2b0a0749c12324e638b57

emoncms_history:
  api_key: 278d467f3140f10fb6004a49502c01f1
  url: http://192.168.5.178/emoncms
  inputnode: 1
  whitelist:
    - sensor.combined_energy_total
    - sensor.watts1_energy_power
    - sensor.watts2_energy_power
    - sensor.bedroom_temperature
    - sensor.closet_temperature
    - sensor.kitchen_temperature
    - sensor.house_temperature
    - sensor.watts1_ds18b20_temperature
    - sensor.barometric_pressure
    - sensor.watts1_energy_frequency
    - sensor.watts1_energy_voltage
    - sensor.watts2_energy_frequency
    - sensor.watts2_energy_voltage

#################################################################
## DB Logging for sensors
#################################################################
influxdb:
  host: 192.168.5.155
  include:
    entities:
    - sensor.barometric_pressure
    - sensor.bedroom_temperature
    - sensor.closet_temperature
    - binary_sensor.front_door_ding
    - binary_sensor.front_door_motion
    - sensor.house_temperature
    - sensor.kitchen_temperature
    - sensor.ups_load
    - sensor.watts1_energy_power
    - sensor.watts1_energy_today
    - sensor.watts1_energy_total
    - sensor.watts1_energy_yesterday
    - sensor.watts2_energy_power
    - sensor.watts2_energy_today
    - sensor.watts2_energy_total
    - sensor.watts2_energy_yesterday
    - sensor.watts1_ds18b20_temperature
    - sensor.combined_energy_total
  component_config_glob:
    sensor.*humidity:
      override_measurement: humidity
    sensor.*temperature:
      override_measurement: temperature
    sensor.*pressure:
      override_measurement: pressure
    sensor.*power:
      override_measurement: watts
    sensor.*motion:
      override_measurement: motion
    sensor.*ding:
      override_measurement: ring
    sensor.*load:
      override_measurement: percentage
    sensor.*energy_total:
      override_measurement: kWH
    sensor.*energy_today:
      override_measurement: kWH
    sensor.*energy_yesterday:
      override_measurement: kWH


#################################################################
## Includes
#################################################################

sensor: !include sensors.yaml
input_boolean: !include input_boolean.yaml
switch: !include switch.yaml
binary_sensor: !include binsensor.yaml
logbook:
  exclude:
    entity_globs:
      - automation.publish*
#################################################################
## Groups
#################################################################
light:
  - platform: group
    name: Pendant
    entities:
      - light.hue_beyond_down_1
      - light.hue_beyond_down_2
      - light.hue_beyond_down_3


  - platform: group
    name: FloorLamp
    entities:
      - light.floor_lamp_1
      - light.floor_lamp_2

#################################################################
## HVAC
#################################################################
climate:
  - platform: tasmota_irhvac
    name: "lg"
    command_topic: "cmnd/irhub/IRhvac"
    state_topic: "tele/irhub/RESULT"
    temperature_sensor: sensor.bedroom_temperature
    protocol: "LG"
    min_temp: 16 #optional - default 16 int value
    max_temp: 32 #optional - default 32 int value
    target_temp: 26 #optional - default 26 int value
    initial_operation_mode: "off" # optional - default "off" string value (one of the "supported_modes")
    away_temp: 24 #optional - default 24 int value
    precision: 1 #optional - default 1 int or float value. Can be set to 1, 0.5 or 0.1
    supported_modes:
      - "heat"
      - "cool"
      - "dry"
      - "fan_only"
      - "auto"
      - "off" #Turns the AC off - Should be quoted
      # Some devices have "auto" and "fan_only" chaned
      # If following two lines are uncommented, "auto" and "fan" shoud be commented
      #- auto_fan_only #if remote shows fan but tasmota says auto
      #- fan_only_auto #if remote shows auto but tasmota says fan
    supported_fan_speeds:
      # Some devices say max,but it is high, and auto which is max
      # If you uncomment the following two, you have to comment high and max
      # - auto_max #woud become max
      # - max_high #would become high
      #- on
      #- off
      #- low
      - "medium"
      - "high"
      #- middle
      #- focus
      #- diffuse
      - "min"
      - "max"
      #- auto
    supported_swing_list:
      - "off"
      - "vertical" #up to down
      # - horizontal # Left to right
      # - both
    default_quiet_mode: "Off" #optional - default "Off" string value
    default_turbo_mode: "Off" #optional - default "Off" string value
    default_econo_mode: "Off" #optional - default "Off" string value
    hvac_model: "-1" #optional - default "1" string value
    celsius_mode: "On" #optional - default "On" string value
    default_light_mode: "Off" #optional - default "Off" string value
    default_filter_mode: "Off" #optional - default "Off" string value
    default_clean_mode: "Off" #optional - default "Off" string value
    default_beep_mode: "Off" #optional - default "Off" string value
    default_sleep_mode: "-1" #optional - default "-1" string value
