#################################################################
##  Switches
#################################################################
- platform: command_line
  switches:
    bedroom_dehumidifier:
        command_on: /usr/bin/curl -g http://192.168.5.4/cm?cmnd=IRhvac%20{"Vendor":"LG","Model":1,"Power":"On","Mode":"Dry","FanSpeed":"Medium","Temp":"24"}
        command_off: /usr/bin/curl -g http://192.168.5.4/cm?cmnd=IRhvac%20{"Vendor":"LG","Model":1,"Power":"Off"}
        friendly_name: "Bedroom Dehumidifier"



#################################################################
##  Template Switches
#################################################################




        ##########################################################
        ##Study AC
        ##########################################################
